version: 0.2

proxy:
  upload-artifacts: yes
  logs: yes

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - echo Start installing NPM dependencies at `date`
    - npm install
    finally:
    - echo Install dependencies finished at `date`
  pre_build:
    commands:
    - command
    - command
    finally:
    - command
    - command
  build:
    commands:
    - echo Start Zipping Code at `date
    - zip nodejs-tutorial.zip -r * .[^.]* -x .idea .gitignore eb-node-express-sample.iml
    finally:
    - echo Zipping code finished at `date`
  post_build:
    commands:
    - echo Start Sending zip to Elastic Beanstalk at `date`
    - command
    finally:
    - echo Zip sended to Elastic Beanstalk at `date`
artifacts:
  files:
  - nodejs-tutorial.zip
  name: nodejs-tutorial-$(date).zip
  discard-paths: yes
  base-directory: .
