version: 0.2

proxy:
  upload-artifacts: yes
  logs: yes

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - echo Start installing NPM dependencies at `date`
    - npm install
    finally:
    - echo Install dependencies finished at `date`
  build:
    commands:
    - npm build
artifacts:
  files:
  - '**/*'
